### ISSUE TITLE
Cant build project using the nuget package because the path to a dll is incorrect

### ISSUE THREAD

**Issue by henkgl** [hms-networks/ixxat-vci4-dotnet-wrapper#5]
error MSB3030: Could not copy the file ".nuget\packages\ixxat.vci4\4.1.8\build\netcoreapp3.1\arm\vcinet.arm64.dll" because it was not found.

This is caused by the incorrect path in:
https://github.com/hms-networks/ixxat-vci4-dotnet-wrapper/blob/main/nuget/build/Ixxat.Vci4.NetCore.targets

**Comment by HMS-klob** [comment]
Sorry, copy/paste hit. Fixed in 4.1.9.

**Comment by henkgl** [comment]
Thanks for the quick fix. I think something went wrong when making the nuget package. The .targets file still is incorrect:
https://www.nuget.org/api/v2/package/Ixxat.Vci4/4.1.9

**Comment by HMS-klob** [comment]
Sorry, had a glitch with Jenkins not picking up the latest commit. Released 4.1.10 after double checking the package contents.

**Comment by SoftEntwickler** [comment]
Nuget Ixxat.Vci4 (4.1.10)

Still an issue for me.
After trying to get the device list by

`  var deviceList = VciServer.Instance().DeviceManager.GetDeviceList();
`
I got the following exception:

> System.InvalidOperationException: 'Did not find platform specific assembly (vcinet\x64\vcinet.x64.dll) in 
> C:\Repos\Uebungen\WinFormsApp3\WinFormsApp3\bin\Debug\net9.0-windows\vcinet\x64\vcinet.x64.dll or 
> C:\Repos\Uebungen\WinFormsApp3\WinFormsApp3\bin\Debug\net9.0-windows\vcinet\x64\vcinet.x64.dll. Check your installation.'

The file vcinet.x64.dll is in my output directory but not in the sub directory  vcinet\x64.

Additionally when I use the .NetFramework 4.8 and copy the file by hand to the sub directory it seams to work,
but when I try use the .Net 9.0 and also copy the file by hand I get an other exception:

> Could not load file or assembly 'C:\Repos\Uebungen\WinFormsApp3\WinFormsApp3\bin\Debug\net9.0-windows\vcinet\x64\vcinet.x64.dll'. Format of the executable (.exe) or library (.dll) is invalid.

Please reopen this issue.

**Comment by henkgl** [comment]
We strangely don't encounter this issue. The call to `VciServer.Instance()` goes without problems while the native DLLs reside in the output folder (not subfolder). Based on what I can see, VciServer.Instance() should also throw the `InvalidOperationException` exception for us. (We use .NetFramework 4.8)

The solution is to use:
```xml
<Content Include="$(MSBuildThisFileDirectory)\x86\vcinet.x86.dll">
   <CopyToOutputDirectory>Always</CopyToOutputDirectory>
   <Link>\vcinet\x86\%(Filename)%(Extension)</Link>
</Content>
...
```
(Something like this. I didn't test it)

ref:
https://github.com/dotnet/msbuild/issues/2795

**Comment by SoftEntwickler** [comment]
Please try with a fresh VisualStudio 2022 Project and Ixxat.Vci4 (4.1.10) NuGet.

**Comment by henkgl** [comment]
Ah, we actually do have an issue with this. Apparently we did not test that specific branch yet.

**Comment by SoftEntwickler** [comment]
Additionally a fresh .Net 9 Project with the NuGet-package must be checked.
I'm currently using .Net9.0.

**Comment by SoftEntwickler** [comment]
The error seams to be in the file vcisrv.cs Line 155:

`string assemblyName = "vcinet\\" + archstr + "\\vcinet." + archstr + ".dll";`

**Comment by HMS-klob** [comment]
Fixed in 4.1.11.
